version: '3.3'
networks:
  nodeNet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.1/28
          gateway: 172.25.0.1
services:
  domus-openhab:
    image: openhab/openhab:3.4.1 # Last stable version of openhab available on docker hub
    restart: always # Restart the container if it crashes
    ports:
      - 8080:8080 # Openhab web interface
      - 8443:8443 # Openhab web interface with TLS
      - 8883:8883 # MQTT port with TLS
      - 1883:1883 # MQTT port
    volumes:  # Mount the configuration files
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./openhab_addons:/openhab/addons:rw
      - ./appartement:/openhab/conf:rw
      - ./openhab_userdata:/openhab/userdata:rw
    environment:  # Set the environment variables
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
    networks:
      nodeNet:
        ipv4_address: 172.25.0.3
  domus-mqtt-broker:
    image: eclipse-mosquitto:1.6.10
    volumes:
      - ./broker_config/:/mosquitto/config/
      - ./broker_certs/:/etc/mosquitto/certs/
      - ./password_file:/etc/mosquitto/passwd
    restart: unless-stopped
    ports:
      - 8884:8883
    networks:
      nodeNet:
        ipv4_address: 172.25.0.2