version: '3.3'
networks:
  nodeNet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.1/28
services:
  domus-mqtt-broker:
    image: eclipse-mosquitto:1.6.10
    volumes:
      - ./broker_config/:/mosquitto/config/
      - ./broker_certs/:/etc/mosquitto/certs/
      - ./password_file:/etc/mosquitto/passwd
    restart: unless-stopped
    ports:
      - 8884:8883
    networks:
      nodeNet:
        ipv4_address: 172.25.0.2